Fiorella/Models/Layout.cs
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Fiorella.Models
{
    public class Layout : BaseEntity
    {
        [Required]
        [MaxLength(25)]
        public string Logo { get; set; }
        public string facebook_url { get; set; }
        public string twitter_url { get; set; }
        [NotMapped]
        public IFormFile file { get; set; }
    }
}

Fiorella/Areas/Admin/Controllers/CategoryController.cs
using Fiorella.DAL;
using Fiorella.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace Fiorella.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly AppDbContext _context;
        public CategoryController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var categories = await _context.Categories.ToListAsync();
            return View(categories);
        }

        public async Task<IActionResult> Detail(int id)
        {
            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Category category)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            await _context.Categories.AddAsync(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Update(int id)
        {
            Category category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id, Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _context.Categories.Update(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }


            return View(category);
        }

        public async Task<IActionResult> Delete(int id)
        {
            Category category = await _context.Categories.FindAsync(id);

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteCategory(int id)
        {
            Category category = await _context.Categories.FindAsync(id);

            if (category == null)
            {
                return NotFound();
            }
            _context.Categories.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }


    }
}

Fiorella/Areas/Admin/Controllers/LayoutController.cs
using Fiorella.DAL;
using Fiorella.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.IO;
using System.Threading.Tasks;

namespace Fiorella.Areas.Admin.Controllers
{
    public class LayoutController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;
        public LayoutController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public async Task<IActionResult> Index()
        {
            var layouts = await _context.Layout.ToListAsync();

            return View(layouts);
        }

        public async Task<IActionResult> Detail(int id)
        {
            var layoutI = await _context.Layout.FindAsync(id);
            if (layoutI == null)
            {
                return NotFound();
            }
            return View(layoutI);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Layout lyt)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            if (!lyt.file.ContentType.Contains("image"))
            {
                ModelState.AddModelError(nameof(lyt.file), "Not valid");
                return View(lyt);
            }

            if (lyt.file.Length > 1024 * 1000)
            {
                ModelState.AddModelError(nameof(lyt.file), "File size cannot be greater than 1 mb!");
                return View(lyt);
            }
            string fileName = Guid.NewGuid() + lyt.file.FileName;
            string wwwRoot = _env.WebRootPath;

            var path = Path.Combine(wwwRoot, "img", fileName);
            FileStream fileStream = new FileStream(path, FileMode.Create);
            await lyt.file.CopyToAsync(fileStream);
            fileStream.Close();

            await _context.Layout.AddAsync(lyt);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {

            Layout layout = await _context.Layout.FindAsync(id);

            if (layout == null)
            {
                return NotFound();
            }

            return View(layout);

        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> DeleteCategory(int id)
        {

            Layout layout = await _context.Layout.FindAsync(id);

            if (layout == null)
            {
                return NotFound();
            }
            _context.Layout.Remove(layout);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }



    }
}

Fiorella/Areas/Admin/Views/Layout/Create.cshtml
@model Layout

<div class="row">
    <div class="col-12">
        <h1>New category</h1>
        <form class="forms-sample" method="post" asp-controller="Layout" asp-action="Create">
           <div class="form-group">
               <label asp-for="Logo">Enter Name</label>
               <input asp-for="Logo" placeholder="Enter Title">
               <span class="text-danger" asp-validation-for="Logo"></span>
           </div>
           <div class="form-group">
               <label asp-for="facebook_url">Enter Name</label>
               <input asp-for="facebook_url" placeholder="Enter Facebook Url">
               <span class="text-danger" asp-validation-for="facebook_url"></span>
           </div>
           <div class="form-group">
               <label asp-for="twitter_url">Enter Name</label>
               <input asp-for="twitter_url" placeholder="Enter Twitter Url">
               <span class="text-danger" asp-validation-for="twitter_url"></span>
           </div>
           <div class="form-group">
               <button type="submit" class="btn btn-primary">Submit</button>
           </div>
        </form>
    </div>
</div>

Fiorella/Areas/Admin/Views/Layout/Delete.cshtml
@Model Layout

@{
    ViewData["Title"] = "Delete";
}


<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
                  <div class="card">
                    <div class="card-body">
                      <h4 class="card-title">@Model.Logo</h4>
                    </div>
                    <form method="post" asp-controller="Layout" asp-action="Delete">
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                  </div>
                </div>
</div>

Fiorella/Areas/Admin/Views/Layout/Detail.cshtml
@model Layout

<div class="content-wrapper">
    <div class="row">
        <div class="col-md-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Category</h4>
                    <p class="card-description">
                        @Model.Logo
                        @Model.facebook_url
                        @Model.twitter_url
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

Fiorella/Areas/Admin/Views/Layout/Index.cshtml
@model List<Layout>

<div class="content-wrapper">
    <div class="row">
        <div class="col-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Basic Table</h4>
                    <p class="card-description">
                        Add class <code>.table</code>
                    </p>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Name</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model) { 
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>@item.Logo</td>
                                        <td>@item.facebook_url</td>
                                        <td>@item.twitter_url</td>

                                        <td><a class="btn btn-primary" asp-area="Admin" asp-controller="Category" asp-action="Index" asp-route-id="@item.Id">
                                            Details
                                        </a></td>
                                        <td> <a class="btn btn-success"  asp-area="Admin" asp-controller="Category" asp-action="Update" asp-route-id="@item.Id">
                                            Update
                                        </a></td>
                                        <td>   <a class="btn btn-danger"  asp-area="Admin" asp-controller="Category" asp-action="Delete" asp-route-id="@item.Id">
                                            Delete
                                        </a></td>
                                     
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>