Fiorella/Models/SliderImage.cs
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations.Schema;

namespace Fiorella.Models
{
    public class SliderImage : BaseEntity
    {
        public string Image { get; set; }

        [NotMapped]
        public IFormFile File { get; set; }
        public int SliderId { get; set; }
        public Slider slider { get; set; }
    }
}

Fiorella/Areas/Admin/Controllers/CategoryController.cs
using Fiorella.DAL;
using Fiorella.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace Fiorella.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly AppDbContext _context;
        public CategoryController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var categories = await _context.Categories.ToListAsync();
            return View(categories);
        }

        public async Task<IActionResult> Detail(int id)
        {
            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Category category)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            await _context.Categories.AddAsync(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Update(int id)
        {
            Category category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id, Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _context.Categories.Update(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }


            return View(category);
        }

        public async Task<IActionResult> Delete(int id)
        {
            Category category = await _context.Categories.FindAsync(id);

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteCategory(int id)
        {
            Category category = await _context.Categories.FindAsync(id);

            if (category == null)
            {
                return NotFound();
            }
            _context.Categories.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }


    }
}

Fiorella/Areas/Admin/Controllers/SliderImageController.cs
using Fiorella.Areas.Admin.Controllers.Constants;
using Fiorella.Areas.Admin.Utils;
using Fiorella.Areas.Admin.ViewModels;
using Fiorella.DAL;
using Fiorella.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.IO;
using System.Threading.Tasks;

namespace Fiorella.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SliderImageController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;
        public SliderImageController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public async Task<IActionResult> Index()
        {
            var sliderImgs = await _context.SliderImages.ToListAsync();
            return View(sliderImgs);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Create")]
        public async Task<IActionResult> CreateSliderImage(SliderImage sliderImage)
        {

            if (!ModelState.IsValid)
            {
                return View();
            }

            if (!sliderImage.File.IsContains())
            {
                ModelState.AddModelError(nameof(SliderImage), "File is not supported");
                return View();
            }

            if (sliderImage.File.IsRightSize(1000))
            {
                ModelState.AddModelError(nameof(File), "Size can not be greater than 1mb.");
            }

            sliderImage.Image = FileUtils.FileCreate(sliderImage.File);

            await _context.SliderImages.AddAsync(sliderImage);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));

        }

        public async Task<IActionResult> Update(int id)
        {
            
            SliderImage slider = await _context.SliderImages.FindAsync(id);
            if (slider == null)
            {
                return BadRequest();
            }
            return View(slider);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Update")]
        public async Task<IActionResult> UpdateSlider(int id, SliderImage sliderImage)
        {

            if (!ModelState.IsValid)
            {
                return View();
            }

            if (id != sliderImage.Id)
            {
                return NotFound();
            }

            if (!sliderImage.File.IsContains())
            {
                ModelState.AddModelError(nameof(SliderImage), "File is not supported.");
                return View();
            }
            if (sliderImage.File.IsRightSize(1000))
            {
                ModelState.AddModelError(nameof(SliderImage), "Size can not be greater than 1mb.");

            }

            var slider = await _context.SliderImages.FindAsync(id);
            string path = Path.Combine(FileConstants.ImagePath, slider.Image);

            slider.Image = FileUtils.FileCreate(sliderImage.File);

            _context.SliderImages.Update(slider);
            await _context.SaveChangesAsync();



            return RedirectToAction(nameof(Index));

        }

        public async Task<IActionResult> Delete(int id)
        {
            SliderImage sliderImage = await _context.SliderImages.FindAsync(id);
            if (sliderImage == null)
            {
                return NotFound();
            }
            return View(sliderImage);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteSliderImage(int id)
        {
            SliderImage sliderImage = await _context.SliderImages.FindAsync(id);
            if (sliderImage == null)
            {
                return NotFound();
            }

            string path = Path.Combine(FileConstants.ImagePath, sliderImage.Image);

            _context.SliderImages.Remove(sliderImage);
            await _context.SaveChangesAsync();
            FileUtils.FileDelete(path);
            return RedirectToAction(nameof(Index));
        }

        //public IActionResult AddSliderToSliderImages()
        //{
        //    return View();
        //}

        //[HttpPost]
        //public async Task<IActionResult> AddSlider(MultipleViewModel viewModel)
        //{

        //    if (!ModelState.IsValid)
        //    {
        //        return View();
        //    }

        //    var slider = new Slider { Title = "Title", Description = "Description", Sign = "Sign" };
        //    await _context.Slider.AddAsync(slider);
        //    await _context.SaveChangesAsync();

        //    foreach (var item in viewModel.files)
        //    {
        //        if (!item.IsContains())
        //        {
        //            ModelState.AddModelError(nameof(SliderImage), "File is not supported.");
        //            return View();
        //        }

        //        if (item.IsRightSize(1000))
        //        {
        //            ModelState.AddModelError(nameof(SliderImage), "Size can not be greater than 1mb.");

        //        }

        //        viewModel.Slider.Sign = FileUtils.FileCreate(viewModel.Slider.signFile);

        //        //await _context.SliderImages.AddAsync();
                
        //    }
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction();

        //}

    }
}

Fiorella/Areas/Admin/Views/SliderImage/Create.cshtml
@model SliderImage
@{
    ViewData["Title"] = "Create";
}

<div class="content-wrapper">
    <div class="row">
    <div class="col-md-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Default form</h4>
                <p class="card-description">
                    Create Slider Image
                </p>
                <form class="forms-sample" method="post" asp-action="Create" enctype="multipart/form-data">

                    <div class="form-group">
                        <label asp-for="File"></label>
                        <input class="form-control" asp-for="File" id="exampleInputUsername1" placeholder="Name" accept="image/*">
                        <span asp-validation-for="File"></span>
                    </div>

                    <button type="submit" class="btn btn-primary me-2">Submit</button>
                    <button class="btn btn-light" asp-controller="SliderImage" asp-action="Index">Cancel</button>

                </form>
            </div>
        </div>
    </div>
</div>
</div>

Fiorella/Areas/Admin/Views/SliderImage/Delete.cshtml
@model SliderImage
@{
    ViewData["Title"] = "Delete";
}

<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
                  <div class="card">
                    <div class="card-body">
                      <img src="~/img/@Model.Image"/>
                    </div>
                    <form method="post" asp-controller="SliderImage" asp-action="Delete">
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                  </div>
                </div>
</div>

Fiorella/Areas/Admin/Views/SliderImage/Index.cshtml
@model List<SliderImage>
@{
    ViewData["Title"] = "Index";
}

<div class="content-wrapper">
    <div class="row">
        <div class="col-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Basic Table</h4>
                    <p class="card-description">
                        Add class <code>.table</code>
                    </p>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Image</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td> <img src="~/img/@item.Image" alt="Alternate Text" style="width: 200px; height: 200px; object-fit:cover; object-position:center;"/></td>
                                        <td>
                                            <a class="btn btn-primary" asp-area="Admin" asp-controller="SliderImage" asp-action="Index" asp-route-id="@item.Id">
                                                Details
                                            </a>
                                        </td>
                                        <td>
                                            <a class="btn btn-success" asp-controller="SliderImage" asp-action="Update" asp-route-id="@item.Id">
                                                Update
                                            </a>
                                        </td>
                                        <td>
                                            <a class="btn btn-danger" asp-controller="SliderImage" asp-action="Delete" asp-route-id="@item.Id">
                                                Delete
                                            </a>
                                        </td>

                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Fiorella/Areas/Admin/Views/SliderImage/SliderCreation.cshtml
@model MultipleViewModel
@{
    ViewData["Title"] = "SliderCreation";
}

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Slider Creation Form</h4>
            <form class="forms-sample" enctype="multipart/form-data" method="post" asp-controller="SliderImage" asp-action="AddMultipleSlider">
                <div class="form-group">
                    <label for="exampleInputUsername1" asp-for="files">Name</label>
                    <input type="file" accept="image/*" multiple class="form-control" asp-for="files" placeholder="Image">
                    <span class="text-danger" asp-validation-for="files"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2">Submit</button>
            </form>
        </div>
    </div>
</div>

Fiorella/Areas/Admin/Views/SliderImage/Update.cshtml
@model SliderImage
@{
    ViewData["Title"] = "Update";
}

<div class="row">
    <div class="col-md-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Default form</h4>
                <p class="card-description">
                    Create Category
                </p>
                <form class="forms-sample" method="post" asp-action="Update" enctype="multipart/form-data">

                    <div class="form-group">
                        <label asp-for="File"></label>
                        <input class="form-control" asp-for="File" id="exampleInputUsername1" placeholder="Name" accept="image/*">
                        <span asp-validation-for="File"></span>
                    </div>

                    <button type="submit" class="btn btn-primary me-2">Submit</button>
                    <button class="btn btn-light" asp-controller="Category" asp-action="index">Cancel</button>

                </form>
            </div>
        </div>
    </div>
</div>